// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewConsultarEstadoParams creates a new ConsultarEstadoParams object
// with the default values initialized.
func NewConsultarEstadoParams() *ConsultarEstadoParams {
	var ()
	return &ConsultarEstadoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewConsultarEstadoParamsWithTimeout creates a new ConsultarEstadoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewConsultarEstadoParamsWithTimeout(timeout time.Duration) *ConsultarEstadoParams {
	var ()
	return &ConsultarEstadoParams{

		timeout: timeout,
	}
}

// NewConsultarEstadoParamsWithContext creates a new ConsultarEstadoParams object
// with the default values initialized, and the ability to set a context for a request
func NewConsultarEstadoParamsWithContext(ctx context.Context) *ConsultarEstadoParams {
	var ()
	return &ConsultarEstadoParams{

		Context: ctx,
	}
}

// NewConsultarEstadoParamsWithHTTPClient creates a new ConsultarEstadoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewConsultarEstadoParamsWithHTTPClient(client *http.Client) *ConsultarEstadoParams {
	var ()
	return &ConsultarEstadoParams{
		HTTPClient: client,
	}
}

/*ConsultarEstadoParams contains all the parameters to send to the API endpoint
for the consultar estado operation typically these are written to a http.Request
*/
type ConsultarEstadoParams struct {

	/*IDUsuario
	  Id del usuario

	*/
	IDUsuario string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the consultar estado params
func (o *ConsultarEstadoParams) WithTimeout(timeout time.Duration) *ConsultarEstadoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the consultar estado params
func (o *ConsultarEstadoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the consultar estado params
func (o *ConsultarEstadoParams) WithContext(ctx context.Context) *ConsultarEstadoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the consultar estado params
func (o *ConsultarEstadoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the consultar estado params
func (o *ConsultarEstadoParams) WithHTTPClient(client *http.Client) *ConsultarEstadoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the consultar estado params
func (o *ConsultarEstadoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIDUsuario adds the iDUsuario to the consultar estado params
func (o *ConsultarEstadoParams) WithIDUsuario(iDUsuario string) *ConsultarEstadoParams {
	o.SetIDUsuario(iDUsuario)
	return o
}

// SetIDUsuario adds the idUsuario to the consultar estado params
func (o *ConsultarEstadoParams) SetIDUsuario(iDUsuario string) {
	o.IDUsuario = iDUsuario
}

// WriteToRequest writes these params to a swagger request
func (o *ConsultarEstadoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id_usuario
	if err := r.SetPathParam("id_usuario", o.IDUsuario); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
