// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "controlAsistenciaAPI/servicios/camacho/models"
)

// ConsultarEstadoReader is a Reader for the ConsultarEstado structure.
type ConsultarEstadoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConsultarEstadoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConsultarEstadoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewConsultarEstadoBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewConsultarEstadoOK creates a ConsultarEstadoOK with default headers values
func NewConsultarEstadoOK() *ConsultarEstadoOK {
	return &ConsultarEstadoOK{}
}

/*ConsultarEstadoOK handles this case with default header values.

estado actual del usuario
*/
type ConsultarEstadoOK struct {
	Payload *ConsultarEstadoOKBody
}

func (o *ConsultarEstadoOK) Error() string {
	return fmt.Sprintf("[GET /eventos/{id_usuario}/estado][%d] consultarEstadoOK  %+v", 200, o.Payload)
}

func (o *ConsultarEstadoOK) GetPayload() *ConsultarEstadoOKBody {
	return o.Payload
}

func (o *ConsultarEstadoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ConsultarEstadoOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConsultarEstadoBadRequest creates a ConsultarEstadoBadRequest with default headers values
func NewConsultarEstadoBadRequest() *ConsultarEstadoBadRequest {
	return &ConsultarEstadoBadRequest{}
}

/*ConsultarEstadoBadRequest handles this case with default header values.

bad input parameter
*/
type ConsultarEstadoBadRequest struct {
}

func (o *ConsultarEstadoBadRequest) Error() string {
	return fmt.Sprintf("[GET /eventos/{id_usuario}/estado][%d] consultarEstadoBadRequest ", 400)
}

func (o *ConsultarEstadoBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ConsultarEstadoOKBody consultar estado o k body
swagger:model ConsultarEstadoOKBody
*/
type ConsultarEstadoOKBody struct {

	// estado
	Estado models.EstadoUsuario `json:"estado,omitempty"`
}

// Validate validates this consultar estado o k body
func (o *ConsultarEstadoOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEstado(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ConsultarEstadoOKBody) validateEstado(formats strfmt.Registry) error {

	if swag.IsZero(o.Estado) { // not required
		return nil
	}

	if err := o.Estado.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("consultarEstadoOK" + "." + "estado")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ConsultarEstadoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ConsultarEstadoOKBody) UnmarshalBinary(b []byte) error {
	var res ConsultarEstadoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
