// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ConsultarEstado devuelves el estado actual del usuario
*/
func (a *Client) ConsultarEstado(params *ConsultarEstadoParams) (*ConsultarEstadoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConsultarEstadoParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "consultarEstado",
		Method:             "GET",
		PathPattern:        "/eventos/{id_usuario}/estado",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ConsultarEstadoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ConsultarEstadoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for consultarEstado: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TraerEventos traers los eventos de un usuario
*/
func (a *Client) TraerEventos(params *TraerEventosParams) (*TraerEventosOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTraerEventosParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "traerEventos",
		Method:             "GET",
		PathPattern:        "/eventos/{id_usuario}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TraerEventosReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TraerEventosOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for traerEventos: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
