version: '3.7'
services:

  rabbit_mq:
    image: rabbitmq 
    ports: 
      - "5672:5672"
    logging:
      driver: none

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    logging:
      driver: none

  camacho_api:
    build: ./camachoAPI
    environment:
      PORT: '9090'
      HOST: '0.0.0.0'
      MONGO_DB_URL: 'mongodb://mongodb:27017'
    links:
      - mongodb
    ports:
      - '9090:9090'

  evo:
    build: https://github.com/wilsoncrespo/segurito-evo.git
    environment: 
      swagger.assistance.control.url: http://control_asistencia:8080/F3rn4nd0/ControlAsistencia/1.0.0/
    links:
      - control_asistencia
    ports:
      - "8081:8080"
      
  control_asistencia:
    build: ./controlAsistenciaAPI
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
      MESA_PATH: './mocks/'
      MONGO_DB_URL: 'mongodb://mongodb:27017'
      RABBIT_MQ_HOST: 'rabbit_mq'
      RABBIT_MQ_PORT: '5672'
      CAMACHO_API_HOST: camacho_api:9090
    command: >
      bash -c "scripts/generate_mesa_mock.sh
      && scripts/wait_for_rabbitmq.sh control-asistencia-server"
    links:
      - mongodb
      - rabbit_mq
      - camacho_api
    depends_on:
      - mongodb
      - rabbit_mq
    ports:
      - '8080:8080'

  pumari:
    build: ./pumari
    environment:
      PUMARI_PATH: './mocks/'
      RABBIT_MQ_HOST: 'rabbit_mq'
      RABBIT_MQ_PORT: '5672'
    command: >
      bash -c "scripts/generate_pumari_mock.sh
      && scripts/wait_for_rabbitmq.sh cmd"
    links:
      - rabbit_mq
    depends_on:
      - rabbit_mq