// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// EstadoUsuario estado usuario
// swagger:model EstadoUsuario
type EstadoUsuario string

const (

	// EstadoUsuarioTrabajando captures enum value "trabajando"
	EstadoUsuarioTrabajando EstadoUsuario = "trabajando"

	// EstadoUsuarioDescanso captures enum value "descanso"
	EstadoUsuarioDescanso EstadoUsuario = "descanso"

	// EstadoUsuarioNoRegistrado captures enum value "no_registrado"
	EstadoUsuarioNoRegistrado EstadoUsuario = "no_registrado"
)

// for schema
var estadoUsuarioEnum []interface{}

func init() {
	var res []EstadoUsuario
	if err := json.Unmarshal([]byte(`["trabajando","descanso","no_registrado"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		estadoUsuarioEnum = append(estadoUsuarioEnum, v)
	}
}

func (m EstadoUsuario) validateEstadoUsuarioEnum(path, location string, value EstadoUsuario) error {
	if err := validate.Enum(path, location, value, estadoUsuarioEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this estado usuario
func (m EstadoUsuario) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateEstadoUsuarioEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
