// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RegistrarSalidaCreatedCode is the HTTP code returned for type RegistrarSalidaCreated
const RegistrarSalidaCreatedCode int = 201

/*RegistrarSalidaCreated confirmacion creacion de registro

swagger:response registrarSalidaCreated
*/
type RegistrarSalidaCreated struct {
}

// NewRegistrarSalidaCreated creates RegistrarSalidaCreated with default headers values
func NewRegistrarSalidaCreated() *RegistrarSalidaCreated {

	return &RegistrarSalidaCreated{}
}

// WriteResponse to the client
func (o *RegistrarSalidaCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// RegistrarSalidaBadRequestCode is the HTTP code returned for type RegistrarSalidaBadRequest
const RegistrarSalidaBadRequestCode int = 400

/*RegistrarSalidaBadRequest parametro invalido

swagger:response registrarSalidaBadRequest
*/
type RegistrarSalidaBadRequest struct {
}

// NewRegistrarSalidaBadRequest creates RegistrarSalidaBadRequest with default headers values
func NewRegistrarSalidaBadRequest() *RegistrarSalidaBadRequest {

	return &RegistrarSalidaBadRequest{}
}

// WriteResponse to the client
func (o *RegistrarSalidaBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RegistrarSalidaUnauthorizedCode is the HTTP code returned for type RegistrarSalidaUnauthorized
const RegistrarSalidaUnauthorizedCode int = 401

/*RegistrarSalidaUnauthorized codigo de usuario incorrecto

swagger:response registrarSalidaUnauthorized
*/
type RegistrarSalidaUnauthorized struct {
}

// NewRegistrarSalidaUnauthorized creates RegistrarSalidaUnauthorized with default headers values
func NewRegistrarSalidaUnauthorized() *RegistrarSalidaUnauthorized {

	return &RegistrarSalidaUnauthorized{}
}

// WriteResponse to the client
func (o *RegistrarSalidaUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RegistrarSalidaConflictCode is the HTTP code returned for type RegistrarSalidaConflict
const RegistrarSalidaConflictCode int = 409

/*RegistrarSalidaConflict usuario en estado incorrecto para registro de salida

swagger:response registrarSalidaConflict
*/
type RegistrarSalidaConflict struct {
}

// NewRegistrarSalidaConflict creates RegistrarSalidaConflict with default headers values
func NewRegistrarSalidaConflict() *RegistrarSalidaConflict {

	return &RegistrarSalidaConflict{}
}

// WriteResponse to the client
func (o *RegistrarSalidaConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// RegistrarSalidaInternalServerErrorCode is the HTTP code returned for type RegistrarSalidaInternalServerError
const RegistrarSalidaInternalServerErrorCode int = 500

/*RegistrarSalidaInternalServerError error interno

swagger:response registrarSalidaInternalServerError
*/
type RegistrarSalidaInternalServerError struct {
}

// NewRegistrarSalidaInternalServerError creates RegistrarSalidaInternalServerError with default headers values
func NewRegistrarSalidaInternalServerError() *RegistrarSalidaInternalServerError {

	return &RegistrarSalidaInternalServerError{}
}

// WriteResponse to the client
func (o *RegistrarSalidaInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
