// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewRegistrarSalidaParams creates a new RegistrarSalidaParams object
// no default values defined in spec.
func NewRegistrarSalidaParams() RegistrarSalidaParams {

	return RegistrarSalidaParams{}
}

// RegistrarSalidaParams contains all the bound params for the registrar salida operation
// typically these are obtained from a http.Request
//
// swagger:parameters registrarSalida
type RegistrarSalidaParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Datos del usuario
	  In: body
	*/
	Usuario RegistrarSalidaBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRegistrarSalidaParams() beforehand.
func (o *RegistrarSalidaParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body RegistrarSalidaBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("usuario", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Usuario = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
