// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// RegsitrarEntradaHandlerFunc turns a function with the right signature into a regsitrar entrada handler
type RegsitrarEntradaHandlerFunc func(RegsitrarEntradaParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegsitrarEntradaHandlerFunc) Handle(params RegsitrarEntradaParams) middleware.Responder {
	return fn(params)
}

// RegsitrarEntradaHandler interface for that can handle valid regsitrar entrada params
type RegsitrarEntradaHandler interface {
	Handle(RegsitrarEntradaParams) middleware.Responder
}

// NewRegsitrarEntrada creates a new http.Handler for the regsitrar entrada operation
func NewRegsitrarEntrada(ctx *middleware.Context, handler RegsitrarEntradaHandler) *RegsitrarEntrada {
	return &RegsitrarEntrada{Context: ctx, Handler: handler}
}

/*RegsitrarEntrada swagger:route POST /entradas regsitrarEntrada

registra la controlasistencia del personal

registra la controlasistencia del personal por medio de su codigo (7 caracteres)

*/
type RegsitrarEntrada struct {
	Context *middleware.Context
	Handler RegsitrarEntradaHandler
}

func (o *RegsitrarEntrada) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegsitrarEntradaParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// RegsitrarEntradaBody regsitrar entrada body
// swagger:model RegsitrarEntradaBody
type RegsitrarEntradaBody struct {

	// codigo usuario
	// Required: true
	// Max Length: 7
	// Min Length: 7
	CodigoUsuario *string `json:"codigo_usuario"`
}

// Validate validates this regsitrar entrada body
func (o *RegsitrarEntradaBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCodigoUsuario(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RegsitrarEntradaBody) validateCodigoUsuario(formats strfmt.Registry) error {

	if err := validate.Required("usuario"+"."+"codigo_usuario", "body", o.CodigoUsuario); err != nil {
		return err
	}

	if err := validate.MinLength("usuario"+"."+"codigo_usuario", "body", string(*o.CodigoUsuario), 7); err != nil {
		return err
	}

	if err := validate.MaxLength("usuario"+"."+"codigo_usuario", "body", string(*o.CodigoUsuario), 7); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RegsitrarEntradaBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RegsitrarEntradaBody) UnmarshalBinary(b []byte) error {
	var res RegsitrarEntradaBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
