// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Camacho API",
    "title": "Camacho API",
    "contact": {
      "email": "337n4nd0@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/F3rn4nd0/CamachoAPI/1.0.0",
  "paths": {
    "/eventos/{id_usuario}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "traer los eventos de un usuario",
        "operationId": "traerEventos",
        "parameters": [
          {
            "type": "string",
            "description": "Id del usuario",
            "name": "id_usuario",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "lista eventos del usuario",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Eventos"
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        }
      }
    },
    "/eventos/{id_usuario}/estado": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "devuelve el estado actual del usuario",
        "operationId": "consultarEstado",
        "parameters": [
          {
            "type": "string",
            "description": "Id del usuario",
            "name": "id_usuario",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "estado actual del usuario",
            "schema": {
              "type": "object",
              "properties": {
                "estado": {
                  "$ref": "#/definitions/EstadoUsuario"
                }
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        }
      }
    }
  },
  "definitions": {
    "EstadoUsuario": {
      "type": "string",
      "enum": [
        "trabajando",
        "descanso",
        "no_registrado"
      ]
    },
    "Eventos": {
      "type": "object",
      "required": [
        "id",
        "usuario",
        "tipo",
        "fecha"
      ],
      "properties": {
        "fecha": {
          "type": "string",
          "format": "date-time",
          "example": "2016-08-29T09:12:33.001Z"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "tipo": {
          "$ref": "#/definitions/TipoEvento"
        },
        "usuario": {
          "type": "string",
          "example": "FLUNA"
        }
      }
    },
    "TipoEvento": {
      "type": "string",
      "enum": [
        "entrada",
        "salida"
      ]
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Camacho API",
    "title": "Camacho API",
    "contact": {
      "email": "337n4nd0@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/F3rn4nd0/CamachoAPI/1.0.0",
  "paths": {
    "/eventos/{id_usuario}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "traer los eventos de un usuario",
        "operationId": "traerEventos",
        "parameters": [
          {
            "type": "string",
            "description": "Id del usuario",
            "name": "id_usuario",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "lista eventos del usuario",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Eventos"
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        }
      }
    },
    "/eventos/{id_usuario}/estado": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "devuelve el estado actual del usuario",
        "operationId": "consultarEstado",
        "parameters": [
          {
            "type": "string",
            "description": "Id del usuario",
            "name": "id_usuario",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "estado actual del usuario",
            "schema": {
              "type": "object",
              "properties": {
                "estado": {
                  "$ref": "#/definitions/EstadoUsuario"
                }
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        }
      }
    }
  },
  "definitions": {
    "EstadoUsuario": {
      "type": "string",
      "enum": [
        "trabajando",
        "descanso",
        "no_registrado"
      ]
    },
    "Eventos": {
      "type": "object",
      "required": [
        "id",
        "usuario",
        "tipo",
        "fecha"
      ],
      "properties": {
        "fecha": {
          "type": "string",
          "format": "date-time",
          "example": "2016-08-29T09:12:33.001Z"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "tipo": {
          "$ref": "#/definitions/TipoEvento"
        },
        "usuario": {
          "type": "string",
          "example": "FLUNA"
        }
      }
    },
    "TipoEvento": {
      "type": "string",
      "enum": [
        "entrada",
        "salida"
      ]
    }
  }
}`))
}
