// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TraerEventosHandlerFunc turns a function with the right signature into a traer eventos handler
type TraerEventosHandlerFunc func(TraerEventosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TraerEventosHandlerFunc) Handle(params TraerEventosParams) middleware.Responder {
	return fn(params)
}

// TraerEventosHandler interface for that can handle valid traer eventos params
type TraerEventosHandler interface {
	Handle(TraerEventosParams) middleware.Responder
}

// NewTraerEventos creates a new http.Handler for the traer eventos operation
func NewTraerEventos(ctx *middleware.Context, handler TraerEventosHandler) *TraerEventos {
	return &TraerEventos{Context: ctx, Handler: handler}
}

/*TraerEventos swagger:route GET /eventos/{id_usuario} traerEventos

traer los eventos de un usuario

*/
type TraerEventos struct {
	Context *middleware.Context
	Handler TraerEventosHandler
}

func (o *TraerEventos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTraerEventosParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
