// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi API de control de controlasistencia
This is a simple API


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /F3rn4nd0/ControlAsistencia/1.0.0
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <337n4nd0@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
