// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple API",
    "title": "API de control de controlasistencia",
    "contact": {
      "email": "337n4nd0@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/F3rn4nd0/ControlAsistencia/1.0.0",
  "paths": {
    "/entradas": {
      "post": {
        "description": "registra la controlasistencia del personal por medio de su codigo (7 caracteres)",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "registra la controlasistencia del personal",
        "operationId": "registrarEntrada",
        "parameters": [
          {
            "description": "Datos del usuario",
            "name": "usuario",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "codigo_usuario"
              ],
              "properties": {
                "codigo_usuario": {
                  "type": "string",
                  "maxLength": 7,
                  "minLength": 7
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "confirmacion creacion de registro"
          },
          "400": {
            "description": "parametro invalido"
          },
          "401": {
            "description": "codigo de usuario incorrecto"
          },
          "409": {
            "description": "usuario en estado incorrecto para registro de controlasistencia"
          },
          "500": {
            "description": "error interno"
          }
        }
      }
    },
    "/salidas": {
      "post": {
        "description": "registra la salida del personal por medio de su codigo (7 caracteres)",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "registra la salida del personal",
        "operationId": "registrarSalida",
        "parameters": [
          {
            "description": "Datos del usuario",
            "name": "usuario",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "codigo_usuario"
              ],
              "properties": {
                "codigo_usuario": {
                  "type": "string",
                  "maxLength": 7,
                  "minLength": 7
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "confirmacion creacion de registro"
          },
          "400": {
            "description": "parametro invalido"
          },
          "401": {
            "description": "codigo de usuario incorrecto"
          },
          "409": {
            "description": "usuario en estado incorrecto para registro de salida"
          },
          "500": {
            "description": "error interno"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple API",
    "title": "API de control de controlasistencia",
    "contact": {
      "email": "337n4nd0@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/F3rn4nd0/ControlAsistencia/1.0.0",
  "paths": {
    "/entradas": {
      "post": {
        "description": "registra la controlasistencia del personal por medio de su codigo (7 caracteres)",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "registra la controlasistencia del personal",
        "operationId": "registrarEntrada",
        "parameters": [
          {
            "description": "Datos del usuario",
            "name": "usuario",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "codigo_usuario"
              ],
              "properties": {
                "codigo_usuario": {
                  "type": "string",
                  "maxLength": 7,
                  "minLength": 7
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "confirmacion creacion de registro"
          },
          "400": {
            "description": "parametro invalido"
          },
          "401": {
            "description": "codigo de usuario incorrecto"
          },
          "409": {
            "description": "usuario en estado incorrecto para registro de controlasistencia"
          },
          "500": {
            "description": "error interno"
          }
        }
      }
    },
    "/salidas": {
      "post": {
        "description": "registra la salida del personal por medio de su codigo (7 caracteres)",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "registra la salida del personal",
        "operationId": "registrarSalida",
        "parameters": [
          {
            "description": "Datos del usuario",
            "name": "usuario",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "codigo_usuario"
              ],
              "properties": {
                "codigo_usuario": {
                  "type": "string",
                  "maxLength": 7,
                  "minLength": 7
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "confirmacion creacion de registro"
          },
          "400": {
            "description": "parametro invalido"
          },
          "401": {
            "description": "codigo de usuario incorrecto"
          },
          "409": {
            "description": "usuario en estado incorrecto para registro de salida"
          },
          "500": {
            "description": "error interno"
          }
        }
      }
    }
  }
}`))
}
